### ISSUE TITLE
Feature Request : An option where all the recent files are listed is badly needed ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/deepin-editor#17]
Hi,

just installed the recently released deepin-editor ... while test driving I seem to  miss the option of opening recently accessed files ... a quik list of all files that have been recently accessed would be such a relief ...

currently i have to navigate all the way to the file buried deep in the folders in the file manager to open them, and given that my text files are scattered all over my hard disk ... its quite an exercise to navigate all the way to the location of the file to open them.

**How about a 'CLICK (Left Click)' on the "deepin-editor logo" on the taskbar reveals a list of all the recently accessed files ?**

**Comment by z966768** [comment]
This idea is good,we did take note of it.
