### ISSUE TITLE
Feature Request : Transparency control just like its implemented in Deepin Terminal ???

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/deepin-editor#18]
Hi,

Wouldn't it be great if the option to make the deepin-editor transparent (opacity slider) a good feature to have on deepin editor as well ... deepin terminal already has it ... shouldn't be too hard to implement the same on the editor as well ???

thanks.

**Comment by BLumia** [comment]
Hi and currently no plan to implement this feature. Thank you for your feedback!
