### ISSUE TITLE
The highlight of the current line obscures the upper part of Chinese words

### ISSUE THREAD

**Issue by fksad** [linuxdeepin/deepin-editor#20]
![image](https://user-images.githubusercontent.com/10517914/46903630-358f3380-cf0a-11e8-8b76-5dfa893724b7.png)

As the pic shows, the highlitht of current line had blocked the upper part of Chinese words, especially the caso that those words with dot on their top ('高' for instance).

**Comment by z966768** [comment]
我们已经解决了这个问题。
