### ISSUE TITLE
[feature request] 新行自动缩进

### ISSUE THREAD

**Issue by doooooit** [linuxdeepin/deepin-editor#22]
回车到新的一行的时候可以自动缩进到与上一行相同的位置，或者更进一步智能计算缩进，对块体内的行增加一个缩进单位

**Comment by muggleL** [comment]
复议

**Comment by BLumia** [comment]
先标一下，目前没空搞，不过欢迎 PR ..

ps. 新 issue 请考虑创建到 [developer-center](https://github.com/linuxdeepin/developer-center) ，其他各个项目的 issue 面板很少有人注意 - -

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
