### ISSUE TITLE
I can't find the directory named "editor" when build deepin-terminal manually.

### ISSUE THREAD

**Issue by csqshz** [linuxdeepin/deepin-editor#23]
I want to build deepin-terminal manually.
I follow the spec strictly. 
But when I execute the Installation step, "Build editor", I don't find "editor" directory.

https://github.com/linuxdeepin/deepin-editor/blob/master/README.md#installation

Could anyone help me?

Best Regards,
--Laplace

**Comment by csqshz** [comment]
Please help me.

**Comment by tymmesyde** [comment]
I think you just have to do `cd ./deepin-editor`

**Comment by BLumia** [comment]
Sorry for the late response. Did you still have this issue now?

**Comment by z966768** [comment]
I thought that,you should try to type `ls`,then `cd` what you see.

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
