### ISSUE TITLE
Right Clicking A Text Document In Deepin Editor Causes The Program To Close

### ISSUE THREAD

**Issue by praveenpious** [linuxdeepin/deepin-editor#24]
I just installed deepin-editor-1.1-1 package available from the Arch repos. I find that right clicking a text document after opening it using the Deepin Editor causes the Editor to close. Due to this bug, I am not able to copy-paste from text documents i.e. using the mouse.

Same issue posted by someone else over here at https://github.com/linuxdeepin/deepin-editor/issues/21

**Comment by retro-wertz** [comment]
confirmed here (arch)

**Comment by praveenpious** [comment]
Do check out https://github.com/linuxdeepin/developer-center/issues/678 for updates

**Comment by retro-wertz** [comment]
im on 1.2.2

**Comment by praveenpious** [comment]
Confirmed issue not present in 1.2.2. Fresh install recommended.

**Comment by praveenpious** [comment]
Closing the thread because the issue is not present when I did a fresh install of Arch Linux with the Deepin DE. Keep up the good work guys.
