### ISSUE TITLE
执行到sudo ./deepin-editor-daemon后面的  cd ./editor 没有发现editor目录

### ISSUE THREAD

**Issue by Yakumo-Yukari** [linuxdeepin/deepin-editor#25]
执行到sudo ./deepin-editor-daemon后面的 Build editor cd ./editor 没有发现editor目录

有大佬告诉下问题出在哪里了吗？

**Comment by rekols** [comment]
编译的二进制文件在 build 目录下的 deepin-editor .

**Comment by Yakumo-Yukari** [comment]
@rekols 谢谢大佬  明白了  万分感谢
