### ISSUE TITLE
完成Build auto save daemon 里面的步骤后 依然无法顺利进行到Build editor 目录里没有deepin-editor或editor

### ISSUE THREAD

**Issue by Yakumo-Yukari** [linuxdeepin/deepin-editor#26]
@rekols 完成Build auto save daemon 里面的步骤后 依然无法顺利进行到Build editor 目录里没有deepin-editor或editor
![2018-11-24 07 28 38](https://user-images.githubusercontent.com/12076232/48962449-1c72ab80-efbb-11e8-811b-d430e89055e2.png)
![2018-11-24 07 29 14](https://user-images.githubusercontent.com/12076232/48962451-23012300-efbb-11e8-861a-b99cdf385c45.png)
![2018-11-24 07 30 07](https://user-images.githubusercontent.com/12076232/48962454-2694aa00-efbb-11e8-90ef-d9523e5ace07.png)

**Comment by rekols** [comment]
daemon 现在已经没有在使用了。
