### ISSUE TITLE
is it a bug or Is a Minimum Height for Deepin Editor been set in the latest update ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/deepin-editor#27]
Hi,

Turns out after the latest updates i ran (Ver. 1.2.1.1) ... i am unable to reduce the height of the editor window beyond this ... given my screen size this proportion isn't right ...

Could you please provide the freedom to the user to set the desired height of the window ... just as we could before this update ???

![deepinscreenshot_dde-launcher_20181214123510](https://user-images.githubusercontent.com/3283676/49988455-bb783b00-ff9c-11e8-88a7-6a10b0058c80.png)

**Comment by BLumia** [comment]
Hi and thank you for the feedback. We already changed the size limit in the recent version, please update your package and feel free to let us know if you still have this issue :)

**Comment by aiamuzz** [comment]
yes i confirm its fixed ... but the resizing isn't possible be dragging the bottom edge of the window ... i can only adjust the height by dragging the upper edge of the deepin-editor window.

Is this by design ?
or
A Bug ?

**Comment by BLumia** [comment]
More likely a bug, but I cannot reproduce that on my machine. It's not related to this issue so feel free to open another issue and provide more details so others may help you out.

**Comment by aiamuzz** [comment]
sorry ... its working now ...
