### ISSUE TITLE
arabic language is written from left side 

### ISSUE THREAD

**Issue by elswerky** [linuxdeepin/deepin-editor#28]
when i write any letter in english then switch to arabic language ,,deepin editor writes arabic from left side 

it remind me as if i am using word app not  text editor but at least word apps (like libre ffice writer and  ms word ) these apps have an option to move selected text to right or left or center 

but here wow ,deepin editor start typing  arabic language from left 

even gedit types arabic language correctly from right side ,,,,in fact i will stick with gnome text editor for two reasons ( first it supports arabic better ,,, **all deepin apps have problem with arabic**
and also i like save button present in gedit beside close ,minimze buttons ,, it provide rapid access to saving edits by mouse in a simple click 

![photo_2018-12-31_10-09-03](https://user-images.githubusercontent.com/26687459/50556631-4880fb00-0ce4-11e9-83f0-ca4ed4abc620.jpg)

**Comment by z966768** [comment]
I'm sorry for I don't know write arabic should from right side,now we are planning to do this.

**Comment by z966768** [comment]
you should update the libdtkwidget5 and use the latest version
