### ISSUE TITLE
Please add support to files with UTF-8 encoding

### ISSUE THREAD

**Issue by ChristianGrimberg** [linuxdeepin/deepin-editor#29]
__Hi, this editor is a wondefull new solution on Linux Deepin distro, and I very thank you for that!!!__
Can you add support to files with UTF-8 encoding, that supports the use of accents and umlauts, because those characters show them in Chinese alphabet (according to my interpretation)?

_Sorry for my bad english_

**Comment by ChristianGrimberg** [comment]
I'm really sorry, I'm observing that the UTF-8 encoding works correctly, but when you start the editor by default, it places the GB18030 enconding, and my intention is to open it in UTF-8 enconding by default. This would be possible?
> :heart: Deepin

**Comment by ChristianGrimberg** [comment]
Hello, in the new version of Deepin 15.9.1, the editor open by default in UTF-8 enconding. It works great!
I close this issue.

__Very thank you!__

**Comment by soanvig** [comment]
Mine still uses GB18030 encoding
