### ISSUE TITLE
Does not include in menu

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/deepin-editor#3]
I just installed this awesome software on my arch running deepin and can't find it in the menu. Can start it in Terminal though.

Desktop files missing? Maybe just for Arch.

**Comment by alvarosamudio** [comment]
open terminal and copy the following code to execute it `cd /usr/share/deepin-editor/ && ./editor`

**Comment by DasJott** [comment]
I really know, how to start it. It was just not included to the menu ;)
