### ISSUE TITLE
Bug when openning id_rsa.pub file (ssh key)

### ISSUE THREAD

**Issue by lucasgdb** [linuxdeepin/deepin-editor#30]
A bug happened when i tried to open a .pub file

E.g, see below:
![deepinscreenshot_20190119184214](https://user-images.githubusercontent.com/13838273/51432178-8190f900-1c1a-11e9-87c0-5021893f9176.png)

Now, see when i tried to open with other text editor (gedit):
![deepinscreenshot_20190119184257](https://user-images.githubusercontent.com/13838273/51432182-8bb2f780-1c1a-11e9-96ff-2d8f27e66db3.png)

**Comment by z966768** [comment]
Thanks for using,we now have solved it.

**Comment by z966768** [comment]
> A bug happened when i tried to open a .pub file
> 
> E.g, see below:
> ![deepinscreenshot_20190119184214](https://user-images.githubusercontent.com/13838273/51432178-8190f900-1c1a-11e9-87c0-5021893f9176.png)
> 
> Now, see when i tried to open with other text editor (gedit):
> ![deepinscreenshot_20190119184257](https://user-images.githubusercontent.com/13838273/51432182-8bb2f780-1c1a-11e9-96ff-2d8f27e66db3.png)

Thanks for using,we now have solved it.
