### ISSUE TITLE
[feature request] formatting options (possibly using plugins?)

### ISSUE THREAD

**Issue by Pauligrinder** [linuxdeepin/deepin-editor#31]
It would be great to have the option to automatically (or by pressing certain keys) format common file formats. For example if I paste json rest api output, I would want to indent and wrap it. 
In sublime text editor, I could install a plugin that allowed me to do this by highlighting the json and pressing alt+shift+j. It would be really awesome to have this in deepin-editor. I'm suggesting plugins because then anyone could easily extend the functionality. This could also be done using something jq or prettier etc.

**Comment by z966768** [comment]
We now have this feature.
