### ISSUE TITLE
Encoding messed up in cached buffer on Fedora with en_US locale

### ISSUE THREAD

**Issue by cheese** [linuxdeepin/deepin-editor#32]
Step to reproduce:
0) make sure locate set to en_US.UTF-8
1) Start deepin-editor, type a few chinese characters
2) Close deepin-editor
3) Start deepin-editor, again. Then the previous input characters are messed up.
deepin-editor-1.2.6.3

**Comment by z966768** [comment]
> Step to reproduce:
> 0) make sure locate set to en_US.UTF-8
> 
> 1. Start deepin-editor, type a few chinese characters
> 2. Close deepin-editor
> 3. Start deepin-editor, again. Then the previous input characters are messed up.
>    deepin-editor-1.2.6.3
我们最近更新了一下这部分代码,麻烦看一下问题依旧存在吗(

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
