### ISSUE TITLE
xml文件显示不全

### ISSUE THREAD

**Issue by zwpwjwtz** [linuxdeepin/deepin-editor#36]
打开一个较大的xml文件时，内容加载缓慢且不完整。
附上测试文件：
[deepin-editor_test.xml.zip](https://github.com/linuxdeepin/deepin-editor/files/3021909/deepin-editor_test.xml.zip)

**Comment by z966768** [comment]
我们目前使用的qtextedit打开大文件的时候会非常卡，这个属于Qt的bug，正在想办法处理
