### ISSUE TITLE
does not load file when started with file as parameter

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/deepin-editor#4]
deepin-editor someFile  does not load the file on startup. That would be nice!
Help says, you have to put -f for this... is this neccessary?

**Comment by BLumia** [comment]
Hi and this issue is already fixed, please upgrade your package to the most recent version and enjoy! btw we offered an extra `dedit` binary which allow you open file by running `dedit filename`, which will be much faster than entering `deepin-editor filename` :)
