### ISSUE TITLE
UTF-8 encoding problem when opening the editor

### ISSUE THREAD

**Issue by Saduff** [linuxdeepin/deepin-editor#48]
deepin-editor 1.2.6.4

Steps to reproduce:

1. Create a new text file with the content `ä`, save with UTF-8 encoding.
2. Close the editor.
3. Open the text file in deepin-editor. Instead of `ä`, `채` is displayed.

On the bottom right corner, `UTF-8` is selected. However, selecting it again fixes the issue and `ä` will be displayed correctly. The problem is that when opening the editor, the encoding does not seem to be UTF-8 even though it's shown as selected.

**Comment by BLumia** [comment]
Seems the detected encode doesn't matched the displayed one. Will looking into this issue later.

**Comment by htarnacki** [comment]
deepin-editor: 1.2.9.1
1. create new document
![Zaznaczenie_022](https://user-images.githubusercontent.com/49711873/62030026-65cb6880-b1e4-11e9-9708-670f5a66d3db.png)

2. close and open
![Zaznaczenie_023](https://user-images.githubusercontent.com/49711873/62030042-711e9400-b1e4-11e9-905a-23d2252e2992.png)

**Comment by BLumia** [comment]
> deepin-editor: 1.2.9.1
> 
> 1. create new document
>    ![Zaznaczenie_022](https://user-images.githubusercontent.com/49711873/62030026-65cb6880-b1e4-11e9-9708-670f5a66d3db.png)
> 2. close and open
>    ![Zaznaczenie_023](https://user-images.githubusercontent.com/49711873/62030042-711e9400-b1e4-11e9-905a-23d2252e2992.png)

Please provide the raw content of the original text if possible, thanks!

**Comment by htarnacki** [comment]
```
ąęśćźżółń
dasd
as
d
asd
as
d
asd
```
[example.txt](https://github.com/linuxdeepin/deepin-editor/files/3445515/example.txt)

**Comment by banality** [comment]
I encountered the same problem and I found that if I copy something that uses utf-8 into the deepin editor, it will work correctly when I open it again.

**Comment by mahtiankka** [comment]
I have the same problem in the Deep v20 beta. If there are Scandinavian characters in the text like äöå then everything will change to Chinese. The program is apparently trying to guess what type of text it is. I would be happy if this could be fixed in UTF-8 by default.
![UTF8problem](https://user-images.githubusercontent.com/48694735/84794381-d8ad2000-affe-11ea-8aea-c615e27c9d35.png)

**Comment by xmuli** [comment]
It seems to be the same type of problem as [#1761](https://github.com/linuxdeepin/developer-center/issues/1761) , which has been reported.

**Comment by xmuli** [comment]
Already relayed

**Comment by z966768** [comment]
This problem has been resolved in the new version, welcome to use and give feedback

**Comment by Saduff** [comment]
In version 5.6.25, the problem can still be reproduced with the steps in the first post. The only difference is that instead of UTF-8 being displayed at the bottom incorrectly, `Windows-949` is displayed, so it's still guessing the encoding incorrectly. I'd also be happy with a default of UTF-8 like @mahtiankka says.

**Comment by xmuli** [comment]
@z966768 If possible, paste the repaired commit values together (link)

**Comment by z966768** [comment]
[commit](https://github.com/linuxdeepin/deepin-editor/commit/0e7c51fa200a6d8c8a7a474e5bf60e65375da16e)

**Comment by HalfGodJ** [comment]
@Saduff We now sloved this bug.

**Comment by Saduff** [comment]
Yes, it seems fixed in version 5.6.40, can't reproduce it anymore. Thanks everyone. Closing the issue.
