### ISSUE TITLE
[feature request] 显示/复制被编辑文件的全路径

### ISSUE THREAD

**Issue by duanyao** [linuxdeepin/deepin-editor#50]
希望有这样两个功能：
1. 鼠标悬浮在被编辑文件的 tab 上时，显示文件的全路径。
2. 右键点击编辑文件的 tab 时，菜单中有“复制路径”的功能，将全路径复制到剪贴板。

第二个功能类似vs code的“copy path”，如图：

![图片](https://user-images.githubusercontent.com/1684137/59278960-aa7f5c80-8c95-11e9-9bae-4e9c7ce0ed06.png)

**Comment by BLumia** [comment]
@wangjia12

**Comment by z966768** [comment]
我们已经记录了这个需求,感谢你的支持!
