### ISSUE TITLE
Menu translation problems

### ISSUE THREAD

**Issue by roxfr** [linuxdeepin/deepin-editor#51]
There are translation problems (french) for Archlinux, Fedora, etc ...
See picture below

<a href="http://zupimages.net/viewer.php?id=19/25/w94a.png"><img src="https://zupimages.net/up/19/25/w94a.png" alt="" /></a>

<a href="http://zupimages.net/viewer.php?id=19/25/vad6.png"><img src="https://zupimages.net/up/19/25/vad6.png" alt="" /></a>

<a href="http://zupimages.net/viewer.php?id=19/25/pvyd.png"><img src="https://zupimages.net/up/19/25/pvyd.png" alt="" /></a>

<a href="http://zupimages.net/viewer.php?id=19/25/ozrz.png"><img src="https://zupimages.net/up/19/25/ozrz.png" alt="" /></a>

<a href="http://zupimages.net/viewer.php?id=19/25/v98h.png"><img src="https://zupimages.net/up/19/25/v98h.png" alt="" /></a>

**Comment by BLumia** [comment]
Please consider help us translating these project by [join the community translation team on Transifex](https://www.transifex.com/linuxdeepin/public/) :)

**Comment by roxfr** [comment]
Hello,
I am already registered to transifex on the deepin linux project.
I do not understand why the translation does not work on Archlinux ?

<a href="http://zupimages.net/viewer.php?id=19/26/91fd.png"><img src="https://zupimages.net/up/19/26/91fd.png" alt="" /></a>

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/deepin-editor/pull/52

Should be fixed in the next update :)
