### ISSUE TITLE
Create unreadable characters after saving Persian text

### ISSUE THREAD

**Issue by hsabzehmeidani** [linuxdeepin/deepin-editor#54]
Hi
After saving Persian text and closing the text editor, the content is unreadable!
---
An example of Persian text and deepin editor:
**open** > **write** >
```txt
سلام، حال شما خوب است؟
Hello, how are you?
```
**save** > **close** > **open** >
```txt
Ø³Ù„Ø§Ù…ØŒ Ø­Ø§Ù„ Ø´Ù…Ø§ Ø®ÙˆØ¨ Ø§Ø³ØªØŸ
Hello, how are you?
```
**write** >
```txt
Ø³Ù„Ø§Ù…ØŒ Ø­Ø§Ù„ Ø´Ù…Ø§ Ø®ÙˆØ¨ Ø§Ø³ØªØŸ
Hello, how are you?
سلام، حال شما خوب است؟
Hello, how are you?
```
**save** > **close** > **open** >
```txt
Ø³Ù„Ø§Ù…ØŒ Ø­Ø§Ù„ Ø´Ù…Ø§ Ø®ÙˆØ¨ Ø§Ø³ØªØŸ
Hello, how are you?
????? ??? ??? ??? ????
Hello, how are you?
```
**close**

Please see the following:
![deepin-editor-with-persian](https://user-images.githubusercontent.com/46417001/61516901-39149580-aa1b-11e9-87f7-96abc1910eb6.gif)
Thanks.

**Comment by BLumia** [comment]
What if you manually change the encoding to UTF-8 or the one you're using?

Thanks.

cc @zccrs

**Comment by hsabzehmeidani** [comment]
The default is UTF-8.
The first saving of the Persian text in deepin editor is correctly displayed in gedit.
![deepin-gedit](https://user-images.githubusercontent.com/46417001/61518497-e937cd80-aa1e-11e9-9b06-49c287c4a945.png)

**Comment by hsabzehmeidani** [comment]
I changed the system language from "American English" to "Persian فارسی". But the problem remains.
Another problem for the Persian text in Deepin text editor:
- Right arrow key: **move in the left direction!**
- Shift + Right: correct direction.
![right and shift-right](https://user-images.githubusercontent.com/46417001/61529483-ab46a380-aa36-11e9-8e58-86a31f2bd75d.gif)
- Left arrow key: **move in the right direction!**
- Shift + Left: correct direction.
![left and shift-left](https://user-images.githubusercontent.com/46417001/61529495-b4377500-aa36-11e9-9f9f-6f2acd2aae53.gif)
Thanks.

**Comment by z966768** [comment]
@hsabzehmeidani Thanks for using,we now have solved this.
