### ISSUE TITLE
Vim Editor Key Bindings

### ISSUE THREAD

**Issue by Darren-Haynes** [linuxdeepin/deepin-editor#55]
Hello. I see there is an emacs mode for the Deepin editor. Wondering if there is a possibility for a vim keybindings mode to be developed for the editor?

**Comment by BLumia** [comment]
It's possible but currently there are not a ready-to-use vim keybinding. If anyone would like to work on this feature, feel free to send Pull Request :)

**Comment by z966768** [comment]
Feel free to send Pull Request :),LOL.
