### ISSUE TITLE
一个致命的问题，不支持打开很多文本格式的文件啊

### ISSUE THREAD

**Issue by liyujiang-gzu** [linuxdeepin/deepin-editor#59]
系统版本：15.11 desktop
![图片](https://user-images.githubusercontent.com/16816717/64911913-68652b80-d75a-11e9-92c0-606c6e89cef0.png)

无法打开很多文本格式文件，如证书文件.key/.pem。这是一个致命的BUG，号称文本编辑器，却不支持打开很多明明是文本格式的文件，难道是你们是用扩展名限定么？
![图片](https://user-images.githubusercontent.com/16816717/64911898-3227ac00-d75a-11e9-85b7-debc2b8f0011.png)

**Comment by BLumia** [comment]
我不太清楚为啥之前的开发者做了 mimetype （不是扩展名）白名单限制了可打开的文件类型，可能是怕用户编辑了不该编辑的文件吧。

会帮你转达给现在的维护者，感谢反馈。

**Comment by liyujiang-gzu** [comment]
> 白名单限制

谢谢！
MIME白名单限制是怕用户编辑了不该编辑的文件，这就是白担心的吧？毕竟用Linux的普通身份是不误修改系统文件的，而且切换到管理员身份打开说明用户就是想编辑不该编辑的文件。

**Comment by liyujiang-gzu** [comment]
> 怕用户编辑了不该编辑的文件

不让用户编辑某些不该编辑的文件这种考虑是可以有，但是起码要让查看呀，现在连查看都不能，不给写入权限，但是要有读取权限。

**Comment by BLumia** [comment]
> 怕用户编辑了不该编辑的文件，这就是白担心的吧？毕竟用Linux的普通身份是不误修改系统文件的，而且切换到管理员身份打开说明用户就是想编辑不该编辑的文件。

我确实不知道原作者的用意，如果的确好奇的话可以邮件勇哥问一下。编辑器目前将会有比较大结构的重构，我目前没有参与新设计的文件管理器的开发，所以还不能确认新的文件管理器是否也具有这个行为，不过在发布前我可以帮着再次确认一下这个行为有没有改掉 :)

**Comment by liyujiang-gzu** [comment]
@Blumia 谢谢你的及时反馈，也谢谢你帮忙确认一下新版本的这个行为，我觉得这个限制太过于鸡肋，我要修改的很多文本文件都被限制了，比如：.key, .pem, .kml。我现在是另外安装了notepadqq来编辑不能编辑的文件，暂时不用自己编译自用版本了

**Comment by z966768** [comment]
@liyujiang-gzu 我们慢慢支持这些格式的 ono

**Comment by liyujiang-gzu** [comment]
> @liyujiang-gzu 我们慢慢支持这些格式的 ono

谢谢支持，.key、.pem等特殊文本格式，不允许修改，但是应该允许查看吧！

**Comment by z966768** [comment]
Please reopen the issue if there're any new updates.
