### ISSUE TITLE
[Enhancement] Search Show Number of Matches

### ISSUE THREAD

**Issue by abrahammurciano** [linuxdeepin/deepin-editor#62]
I really like the interface of this app, and I'd love to use it as my general purpose lightweight text editor, but one thing I find is sorely lacking is that the editor doesn't show how many results have been found when I search for something in a file.

Can this feature please be added?

**Comment by z966768** [comment]
It's a long process to add a feature from a stranger,I have told PM your idea.
And ,thanks for using!

**Comment by z966768** [comment]
@abrahammurciano It's a long process to add a feature from a stranger,I have told PM your idea.
And ,thanks for using!

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
