### ISSUE TITLE
[Enhancement] RegEx Search

### ISSUE THREAD

**Issue by abrahammurciano** [linuxdeepin/deepin-editor#63]
I don't see any way to search for text with regular expressions, are there any plans to implement this in the future?

**Comment by z966768** [comment]
@abrahammurciano It's a long process to add a feature from a stranger,I have told PM your idea.
And ,thanks for using!

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
