### ISSUE TITLE
[Bug] Cannot open as root

### ISSUE THREAD

**Issue by abrahammurciano** [linuxdeepin/deepin-editor#64]
I am unable to open `deepin-editor` as root. Neither by using `sudo` nor by opening it from an open admin file explorer window.

Here is what happens when I try to open it with `sudo`

    $ sudo deepin-editor 
``` 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
"dtkwidget" can not find qm files
"deepin-editor" can not find qm files
```

This is annoying, since I often need to modify root files, so I have to resort to `nano` or install another text editor, but I like `deepin-editor`.

**Comment by z966768** [comment]
Emmmm,this is annoying that we can open as root.

**Comment by z966768** [comment]
@abrahammurciano We can open deepin-editor as root,emmmm,we can't reproduce this bug.

**Comment by z966768** [comment]
@abrahammurciano We can open deepin-editor as root,it is annoying that we can't reproduce this bug.

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
