### ISSUE TITLE
建议文本编辑控件改用QScintilla

### ISSUE THREAD

**Issue by icevivi** [linuxdeepin/deepin-editor#67]
在打开较大的文本文件时，很慢。
建议改有Qscintilla做为文本编辑器，打开大文件比较快，语法着色也快，还有其它特性。

**Comment by z966768** [comment]
谢谢您的建议，已通知研发人员

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
