### ISSUE TITLE
Deepin file Editor / Does Not Update Tab After Saving File

### ISSUE THREAD

**Issue by mitchellkrogza** [linuxdeepin/deepin-editor#69]
## Describe the bug

After saving a file, the file tab in Editor remains  "Untitled"

**Comment by xmuli** [comment]
@z966768

**Comment by z966768** [comment]
This is a known bug and we are investigating,thank you for your feedback

**Comment by HalfGodJ** [comment]
@mitchellkrogza 
We now solved this problem.
