### ISSUE TITLE
Open a file, leads to corruption of the files

### ISSUE THREAD

**Issue by Foxei** [linuxdeepin/deepin-editor#7]
I am using manjaro 17.11.1, deepin 15.6 and  deepin Editor 1.0.

The following error occurred:
If you open and close a file with the editor **not** store it just open and close. The editor will change the file.
I discovered this bug while working with json files. 
To proof deepin editor will change the file i generated some md5 hashes.
Result: 
```bash
# Original file open in nodepad to keep original
[simon@simon-pc ps10m]$ md5sum raytracer.json 
c3db10289116a34bc9b2a72f5282d474  raytracer.json
# Open and close it with deepin editor, don't hit save
[simon@simon-pc ps10m]$ md5sum raytracer.json 
c2962ad7fe83833fde3ff9d8564d4d36  raytracer.json
# Restore original with notepad
[simon@simon-pc ps10m]$ md5sum raytracer.json 
c3db10289116a34bc9b2a72f5282d474  raytracer.json
```
In my opinion the editor should not touch the file until the user want to save the file.

**Comment by BLumia** [comment]
Seems this issue no longer existed in the most recent version (tested in 1.2.7.3). Feel free to let us know if you still have this issue and I can reopen this issue for ya :)
