### ISSUE TITLE
cant not open editor

### ISSUE THREAD

**Issue by cancer-chain** [linuxdeepin/deepin-editor#76]
/xxx/dtkwidget-2.1.1/build> gdb deepin-editor 
GNU gdb (GDB; openSUSE Tumbleweed) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from deepin-editor...
(No debugging symbols found in deepin-editor)
Missing separate debuginfos, use: zypper install deepin-editor-debuginfo-1.2.9-2.3.x86_64
(gdb) r
Starting program: /usr/bin/deepin-editor 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff15e4640 (LWP 23700)]
[New Thread 0x7fffeb3da640 (LWP 23701)]
"dtkwidget" can not find qm files
"deepin-editor" can not find qm files
^C
Thread 1 "deepin-editor" received signal SIGINT, Interrupt.
0x00007fffeab8644f in ?? () from /usr/lib64/qt5/plugins/styles/breeze.so
(gdb) bt
#0  0x00007fffeab8644f in  () at /usr/lib64/qt5/plugins/styles/breeze.so
#1  0x00007ffff6907293 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#2  0x00007ffff74b64ee in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#3  0x00007ffff690752a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#4  0x00007ffff74e6e44 in QWidgetPrivate::propagatePaletteChange() () at /usr/lib64/libQt5Widgets.so.5
#5  0x00007ffff74e7038 in QWidgetPrivate::setPalette_helper(QPalette const&) () at /usr/lib64/libQt5Widgets.so.5
#6  0x00007ffff74e9cba in QWidget::setPalette(QPalette const&) () at /usr/lib64/libQt5Widgets.so.5
#7  0x00007ffff754b880 in  () at /usr/lib64/libQt5Widgets.so.5
#8  0x00007ffff755386a in  () at /usr/lib64/libQt5Widgets.so.5
#9  0x00007ffff7e62240 in Dtk::Widget::DThemeManager::eventFilter(QObject*, QEvent*) () at /usr/lib64/libdtkwidget.so.2
#10 0x00007ffff6907293 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#11 0x00007ffff74b64ee in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#12 0x00007ffff690752a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#13 0x00007ffff693c77f in QObject::setProperty(char const*, QVariant const&) () at /usr/lib64/libQt5Core.so.5
#14 0x00007ffff7e70f4c in Dtk::Widget::DImageButtonPrivate::updateIcon() () at /usr/lib64/libdtkwidget.so.2
#15 0x00007ffff7e71197 in Dtk::Widget::DImageButton::DImageButton(QWidget*) () at /usr/lib64/libdtkwidget.so.2
#16 0x00007ffff7e76c90 in Dtk::Widget::DWindowMinButton::DWindowMinButton(QWidget*) () at /usr/lib64/libdtkwidget.so.2
#17 0x00007ffff7e9988b in Dtk::Widget::DTitlebarPrivate::init() () at /usr/lib64/libdtkwidget.so.2
#18 0x00007ffff7e9a3ca in Dtk::Widget::DTitlebar::DTitlebar(QWidget*) () at /usr/lib64/libdtkwidget.so.2
#19 0x00007ffff7e9f41f in Dtk::Widget::DMainWindowPrivate::DMainWindowPrivate(Dtk::Widget::DMainWindow*) () at /usr/lib64/libdtkwidget.so.2
#20 0x00007ffff7e9feb7 in Dtk::Widget::DMainWindow::DMainWindow(QWidget*) () at /usr/lib64/libdtkwidget.so.2
#21 0x00005555555c10f4 in  ()
#22 0x000055555559a0d9 in  ()
#23 0x000055555559b29d in  ()
#24 0x00005555555810e3 in main ()

**Comment by YutianGe** [comment]
You can try the latest version
