### ISSUE TITLE
Text editor does not open .sh files

### ISSUE THREAD

**Issue by igatjens** [linuxdeepin/deepin-editor#77]
Deepin's text editor does not open .sh files with the option to open with, nor when double-clicking to open it and choose the option to show.

Attached video showing the problem.

![Captura de pantalla_área-de-selección_20201202163700](https://user-images.githubusercontent.com/66392244/100939883-ab750100-34bc-11eb-9cb8-ca07e8ff1172.gif)

**Comment by HalfGodJ** [comment]
@igatjens 
This is a system bug, here is two  ways to  avoid:
1.Remove the first line '#!bin/bash' from .sh file.
2.Chmod 666.(No execute).

The best solution is waiting for file-manager update.
![Uploading QQ图片20201203093844.jpg…]()

**Comment by igatjens** [comment]
@HalfGodJ
It is easier to first open the Deepin text editor and drag the .sh file to the editor.

**Comment by HalfGodJ** [comment]
@igatjens

**Comment by HalfGodJ** [comment]
@igatjens 
It's hard to explain,we catched this bug two months ago,
that's your video shows,open .sh file but nothing happened.
You could see we do not filter .sh file in code.I find this two 
ways to avoid,and transfer the bug to dde,then they solved.
Pls try one of them,it is probably works.
