### ISSUE TITLE
 黑色皮肤中设置BUG

### ISSUE THREAD

**Issue by BruceWang666** [linuxdeepin/deepin-editor#8]
进入黑色皮肤后，点设置，设置界面还是白色的，而且快捷键的说明文字消失掉，看不到文字（github没法传截图）

**Comment by BLumia** [comment]
直接粘贴即可截图。

目前设置对话框之类的是白色是所有应用一致的行为，等后续所有 DTK 应用统一的主题支持做完就会改。
