### ISSUE TITLE
[Feature request] Change Read-Only behaviour 

### ISSUE THREAD

**Issue by vesterlay** [linuxdeepin/deepin-editor#81]
I find this very annoying, when you open a text file owned by root and you can't edit it directly with a password, but have to close application -> open new window as admin -> edit your file with root privileges. Wouldn't it be better to make it like in sublime text? 

https://user-images.githubusercontent.com/39202451/107298026-e1ae9e00-6a74-11eb-952a-d610f71a658a.mp4

**Comment by z966768** [comment]
Thank you for your suggestions, feedback has been made, any latest news will be replied here

**Comment by guoshaoyu** [comment]
> I find this very annoying, when you open a text file owned by root and you can't edit it directly with a password, but have to close application -> open new window as admin -> edit your file with root privileges. Wouldn't it be better to make it like in sublime text?
> 
>  Screen.Capture_select-area_20210209011638.mp4

Hello, the use logic of the current product is designed like this. We will discuss with the product manager about whether optimization and improvement are needed before making the next improvement plan. Thank you for your proposal.
