### ISSUE TITLE
请不要记住上次打开的文件

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/deepin-editor#86]
理由：泄露隐私。
如果有些人一定要记住上次打开的文件，请做一个开关来设置。

**Comment by YutianGe** [comment]
Thank you for your advice

**Comment by listenerri** [comment]
不同的声音：希望保留此功能，部分编辑中，未保存的文件，会在下次打开时恢复，我觉得这是一个亮点功能

**Comment by guoshaoyu** [comment]
> 理由：泄露隐私。
> 如果有些人一定要记住上次打开的文件，请做一个开关来设置。

感谢您的建议，我们会合理考虑此功能。
