### ISSUE TITLE
选中文字按shift，文字会删除

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/deepin-editor#87]
deepin-editor 5.9.0.49 出现的新问题：选中文字按shift，文字会删除。
其他编辑器没有这个问题。

**Comment by guoshaoyu** [comment]
> deepin-editor 5.9.0.49 出现的新问题：选中文字按shift，文字会删除。
> 其他编辑器没有这个问题。

感谢您的使用，此问题已修复，请更新最新版本使用，谢谢～
