### ISSUE TITLE
sudo deepin-editor会打开小键盘锁

### ISSUE THREAD

**Issue by kt286** [linuxdeepin/deepin-editor#96]
复现步骤
1. 打开一个文本编辑器示例
2. 打开终端
3. sudo deepin-editor

此时会再打开一个文本编辑器示例，同时打开小键盘锁

**Comment by ClayStan** [comment]
已反馈给开发处理，感谢~

**Comment by kt286** [comment]
经过调试发现 `sudo` 调用 `deepin-editor` 时，调用 `Utils::activeWindowFromDock(window->winId())` 方法会报错
` [Debug  ] [  ] call com.deepin.dde.daemon.Dock failed QDBusError("org.freedesktop.DBus.Error.Spawn.ChildExited", "Process com.deepin.dde.daemon.Dock exited with status 2")
此时会打开小键盘锁
`

**Comment by kt286** [comment]
2021-12-17日内测更新后已解决
